# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/claudio/Desktop/FlasHTTP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/claudio/Desktop/FlasHTTP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/claudio/Desktop/FlasHTTP/CMakeFiles /home/claudio/Desktop/FlasHTTP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/claudio/Desktop/FlasHTTP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flashttp_shared

# Build rule for target.
flashttp_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flashttp_shared
.PHONY : flashttp_shared

# fast build rule for target.
flashttp_shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_shared.dir/build.make CMakeFiles/flashttp_shared.dir/build
.PHONY : flashttp_shared/fast

#=============================================================================
# Target rules for targets named flashttp_static

# Build rule for target.
flashttp_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flashttp_static
.PHONY : flashttp_static

# fast build rule for target.
flashttp_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_static.dir/build.make CMakeFiles/flashttp_static.dir/build
.PHONY : flashttp_static/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

benchmarks/benchmark.o: benchmarks/benchmark.c.o
.PHONY : benchmarks/benchmark.o

# target to build an object file
benchmarks/benchmark.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/benchmarks/benchmark.c.o
.PHONY : benchmarks/benchmark.c.o

benchmarks/benchmark.i: benchmarks/benchmark.c.i
.PHONY : benchmarks/benchmark.i

# target to preprocess a source file
benchmarks/benchmark.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/benchmarks/benchmark.c.i
.PHONY : benchmarks/benchmark.c.i

benchmarks/benchmark.s: benchmarks/benchmark.c.s
.PHONY : benchmarks/benchmark.s

# target to generate assembly for a file
benchmarks/benchmark.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/benchmarks/benchmark.c.s
.PHONY : benchmarks/benchmark.c.s

src/common.o: src/common.c.o
.PHONY : src/common.o

# target to build an object file
src/common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_shared.dir/build.make CMakeFiles/flashttp_shared.dir/src/common.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_static.dir/build.make CMakeFiles/flashttp_static.dir/src/common.c.o
.PHONY : src/common.c.o

src/common.i: src/common.c.i
.PHONY : src/common.i

# target to preprocess a source file
src/common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_shared.dir/build.make CMakeFiles/flashttp_shared.dir/src/common.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_static.dir/build.make CMakeFiles/flashttp_static.dir/src/common.c.i
.PHONY : src/common.c.i

src/common.s: src/common.c.s
.PHONY : src/common.s

# target to generate assembly for a file
src/common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_shared.dir/build.make CMakeFiles/flashttp_shared.dir/src/common.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_static.dir/build.make CMakeFiles/flashttp_static.dir/src/common.c.s
.PHONY : src/common.c.s

src/deserializer.o: src/deserializer.c.o
.PHONY : src/deserializer.o

# target to build an object file
src/deserializer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_shared.dir/build.make CMakeFiles/flashttp_shared.dir/src/deserializer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_static.dir/build.make CMakeFiles/flashttp_static.dir/src/deserializer.c.o
.PHONY : src/deserializer.c.o

src/deserializer.i: src/deserializer.c.i
.PHONY : src/deserializer.i

# target to preprocess a source file
src/deserializer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_shared.dir/build.make CMakeFiles/flashttp_shared.dir/src/deserializer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_static.dir/build.make CMakeFiles/flashttp_static.dir/src/deserializer.c.i
.PHONY : src/deserializer.c.i

src/deserializer.s: src/deserializer.c.s
.PHONY : src/deserializer.s

# target to generate assembly for a file
src/deserializer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_shared.dir/build.make CMakeFiles/flashttp_shared.dir/src/deserializer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_static.dir/build.make CMakeFiles/flashttp_static.dir/src/deserializer.c.s
.PHONY : src/deserializer.c.s

src/serializer.o: src/serializer.c.o
.PHONY : src/serializer.o

# target to build an object file
src/serializer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_shared.dir/build.make CMakeFiles/flashttp_shared.dir/src/serializer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_static.dir/build.make CMakeFiles/flashttp_static.dir/src/serializer.c.o
.PHONY : src/serializer.c.o

src/serializer.i: src/serializer.c.i
.PHONY : src/serializer.i

# target to preprocess a source file
src/serializer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_shared.dir/build.make CMakeFiles/flashttp_shared.dir/src/serializer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_static.dir/build.make CMakeFiles/flashttp_static.dir/src/serializer.c.i
.PHONY : src/serializer.c.i

src/serializer.s: src/serializer.c.s
.PHONY : src/serializer.s

# target to generate assembly for a file
src/serializer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_shared.dir/build.make CMakeFiles/flashttp_shared.dir/src/serializer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flashttp_static.dir/build.make CMakeFiles/flashttp_static.dir/src/serializer.c.s
.PHONY : src/serializer.c.s

tests/test.o: tests/test.c.o
.PHONY : tests/test.o

# target to build an object file
tests/test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.c.o
.PHONY : tests/test.c.o

tests/test.i: tests/test.c.i
.PHONY : tests/test.i

# target to preprocess a source file
tests/test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.c.i
.PHONY : tests/test.c.i

tests/test.s: tests/test.c.s
.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.c.s
.PHONY : tests/test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... benchmark"
	@echo "... flashttp_shared"
	@echo "... flashttp_static"
	@echo "... test"
	@echo "... benchmarks/benchmark.o"
	@echo "... benchmarks/benchmark.i"
	@echo "... benchmarks/benchmark.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/deserializer.o"
	@echo "... src/deserializer.i"
	@echo "... src/deserializer.s"
	@echo "... src/serializer.o"
	@echo "... src/serializer.i"
	@echo "... src/serializer.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

